tailwind.config = {
    darkMode: "class",
    theme: {
        extend: {
            "colors": {
                "on-tert-fix": "#001d35",
                "surf-high": "#362720",
                "sec-cont": "#7b3409",
                "on-prim-box": "#572000",
                "on-err-cont": "#ffdad6",
                "error": "#ffb4ab",
                "on-sec-fix-var": "#783207",
                "prim-box": "#ff6b00",
                "surf-var": "#41312a",
                "on-tert-fix-var": "#00497b",
                "prim-fix": "#ffdbcc",
                "tert-fix-dim": "#9ccaff",
                "on-prim": "#561f00",
                "on-prim-fix-var": "#7a3000",
                "on-err": "#690005",
                "surf-bot": "#170b06",
                "surface": "#1d100a",
                "on-sec-fix": "#351000",
                "prim-fix-dim": "#ffb693",
                "on-sec": "#561f00",
                "out-var": "#5a4136",
                "inv-on-surf": "#3d2d26",
                "primary": "#ffb693",
                "sec-fix": "#ffdbcc",
                "err-cont": "#93000a",
                "inv-prim": "#a04100",
                "outline": "#a98a7d",
                "sec-fix-dim": "#ffb693",
                "on-tert": "#003257",
                "tert-cont": "#059eff",
                "surf-tint": "#ffb693",
                "on-sec-cont": "#ffa173",
                "sec": "#ffb693",
                "on-surf-var": "#e2bfb0",
                "tert": "#9ccaff",
                "surf-bright": "#46362e",
                "on-surf": "#f8ddd2",
                "on-tert-cont": "#003357",
                "surf-top": "#41312a",
                "surf-mid": "#2b1c16",
                "tert-fix": "#d0e4ff",
                "inv-surf": "#f8ddd2",
                "on-bg": "#f8ddd2",
                "surf-low": "#261812",
                "background": "#1d100a",
                "on-prim-fix": "#351000",
                "surf-dim": "#1d100a"
            },
            "borderRadius": {
                "DEFAULT": "0.125rem",
                "lg": "0.25rem",
                "xl": "0.5rem",
                "full": "0.75rem"
            },
            "fontFamily": {
                "head": ["Epilogue"],
                "body": ["Inter"],
                "label": ["Space Grotesk"]
            }
        },
    },
};
